name: keypool
baseurl: /keypool
description: A Keyed Pool for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.2.0+24-66458f4b-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
