name: keypool
baseurl: /keypool
description: A Keyed Pool for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.2.0-RC2+9-576b042c-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
