name: keypool
baseurl: /keypool
description: A Keyed Pool for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.1-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
