name: keypool
baseurl: /keypool
description: A Keyed Pool for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.2.0+22-02ce8f9f-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
